name: student-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - matplotlib
      - numpy
      - pandas
      - pyqt6
      - watchdog
      - pydot
      - python-graphviz
